// auto-generated by bsg_ascii_to_rom.py from /home/hyu3/Documents/22024/526/bsg_aes/aes_algorithm_chip/py/rom_rc.txt; do not modify
module rom_rc #(`BSG_INV_PARAM(width_p), `BSG_INV_PARAM(addr_width_p))
(input  [addr_width_p-1:0] addr_i
,output logic [width_p-1:0]      data_o
);
always_comb case(addr_i)
         0: data_o = width_p ' (8'b00000001); // 0x01
         1: data_o = width_p ' (8'b00000010); // 0x02
         2: data_o = width_p ' (8'b00000100); // 0x04
         3: data_o = width_p ' (8'b00001000); // 0x08
         4: data_o = width_p ' (8'b00010000); // 0x10
         5: data_o = width_p ' (8'b00100000); // 0x20
         6: data_o = width_p ' (8'b01000000); // 0x40
         7: data_o = width_p ' (8'b10000000); // 0x80
         8: data_o = width_p ' (8'b00011011); // 0x1B
         9: data_o = width_p ' (8'b00110110); // 0x36
   default: data_o = { width_p { 1'b0 } };
endcase
endmodule
`BSG_ABSTRACT_MODULE(rom_rc)
