// auto-generated by bsg_ascii_to_rom.py from /home/yjc06/ee478/bsg_aes/aes_algorithm_chip/py/rom_rc.txt; do not modify
module rom_rc #(`BSG_INV_PARAM(width_p), `BSG_INV_PARAM(addr_width_p))
(input  [addr_width_p-1:0] addr_i
,output logic [width_p-1:0]      data_o
);
always_comb case(addr_i)
   default: data_o = { width_p { 1'b0 } };
endcase
endmodule
`BSG_ABSTRACT_MODULE(rom_rc)
